modLoader="javafml"
loaderVersion="[4,)"
license="All Rights Reserved"

[[mods]]
modId="riyaposmod"
version="0.0.1"
displayName="Riyapos Mod"
authors="Furyan8x"
description='''My mod to integrate mods in the Riyapos ModPack.'''

[[dependencies.riyaposmod]]
modId="neoforge"
type="required"
versionRange="[21.1.0,)"
ordering="NONE"
side="BOTH"

[[dependencies.riyaposmod]]
modId="minecraft"
type="required"
versionRange="[1.21.1,1.21.2)"
ordering="NONE"
side="BOTH" 